[project]
name = "mcp-sep-job"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.14.0",
    "requests>=2.32.5",
]
